name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build 
      shell: powershell
      run: |
        mkdir ${{ github.workspace }}/build
        dir ${{ github.workspace }}
        dotnet publish SatisfactoryServerGUI.sln --framework netcoreapp3.1 -c Release -o --output "${{ github.workspace }}/build"    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: SatisfactoryServerGUI
        path:  "${{ github.workspace }}/build/"
